name: Workflow for Codecov

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.gitattributes'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements/requirements-dev.txt ]; then pip install -r  requirements/requirements-dev.txt; fi
        if [ -f requirements/requirements-client.txt ]; then pip install -r  requirements/requirements-client.txt; fi
        if [ -f requirements/requirements-server.txt ]; then pip install -r  requirements/requirements-server.txt; fi
  codecov:
    - name: Generate coverage report
      needs: build
      run: |
        pytest -m "not (apitest or dasktest)" --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
