name: Workflow for Codecov

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.gitattributes'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        if [ -f server/requirements.txt ]; then pip install -r server/requirements.txt; fi
        if [ -f client/requirements.txt ]; then pip install -r client/requirements.txt; fi
    - name: Generate coverage report
      run: |
        pytest -m "not apitest" --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
