# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.gitattributes'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements/requirements-dev.txt ]; then pip install -r  requirements/requirements-dev.txt; fi
        if [ -f requirements/requirements-client.txt ]; then pip install -r  requirements/requirements-client.txt; fi
        if [ -f requirements/requirements-server.txt ]; then pip install -r  requirements/requirements-server.txt; fi
  lint:
    - name: Lint with flake8
      needs: build
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  test:
    - name: Test with pytest
      needs: build
      run: |
        pytest -m "not (apitest or dasktest)"
